version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    volumes:
      - data-volume:/data/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
     - upstage-network
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
    - upstage-network
  mosquitto:
    build:
      context: .
      dockerfile: ./system/mqtt_server/Dockerfile
    container_name: mosquitto_container
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
     - upstage-network
  upstage:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./system/upstage:/app
    networks:
      - upstage-network
    depends_on:
      - postgres
      - mongodb
      - mosquitto
  upstage_event_archive:
    build:
      context: .
      dockerfile: Dockerfile.upstage_event_archive
    container_name: upstage_event_archive_container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./system/event_archive:/app
    networks:
      - upstage-network
    depends_on:
      - postgres
      - mongodb
      - mosquitto
  upstage_email:
    build:
      context: .
      dockerfile: Dockerfile.upstage_email
    container_name: upstage_email_container
    ports:
      - "81:80"
      - "444:443"
    volumes:
      - ./system/email:/app
    networks:
      - upstage-network
    depends_on:
      - postgres
      - mongodb
      - mosquitto
  upstage_stats:
    build:
      context: .
      dockerfile: Dockerfile.upstage_stats
    container_name: upstage_stats_container
    ports:
      - "82:80"
      - "445:443"
    volumes:
      - ./system/stats:/app
    networks:
      - upstage-network
    depends_on:
      - postgres
      - mongodb
      - mosquitto

networks:
  upstage-network:
volumes:
  data-volume:
  mongo_data:
  mosquitto_data:
  mosquitto_log:
